name: device_dna
description: A secure device authentication app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  device_info_plus: ^9.0.2
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.6
  encrypt: ^5.0.3
  pointycastle: ^3.7.3
  asn1lib: ^1.5.0 # or the latest version
  leb128: ^1.1.0
  basic_utils: ^5.7.0
  rsa_encrypt: ^2.0.0
  http: ^1.2.2
  app_integrity_checker: ^1.0.5
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#1c1c1c"
  image: assets/images/logo_square.png
  android_12:
    image: assets/images/logo_square.png
  android: true
  ios: true